name: Test

on:
  - push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: "6.24.4"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: "pnpm"
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Check types
        run: pnpm tsc

      - name: Check code styles
        run: pnpm prettier --check './src/**/*.{ts,tsx,css}'
