name: Test

on:
  - push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install Yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn install --pure-lockfile

      - name: Check types
        run: yarn tsc

      - name: Check code styles
        run: yarn prettier --check './src/**/*.{ts,tsx,css}'
